version: '3'
services: 
  app:
    build:
      context: ./node
    container_name: app
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    volumes:
      - ./database/data:/var/lib/mysql
      - ./database/initial.sql:/docker-entrypoint-initdb.d/inital.sql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
  nginx:
    image: nginx:1.15.0-alpine
    container_name: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks: 
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app
networks:
  node-network:
    driver: bridge